### ISSUE TITLE
Request to join org

### ISSUE THREAD

**Issue by RedstoneWizard08** [ISB-Tech-Drive-Coders/Jekyll-Website#5]
Hey, @Ravin-Oli, can I join the GitHub org? Thanks!

**Comment by RedstoneWizard08** [comment]
*Mostly I want to update the website xD*

**Comment by Ravin-Oli** [comment]
I sent you a invite for the organization

**Comment by Ravin-Oli** [comment]
I was trying to update it, but Vscode kept giving me a error...time for new gpg keys lol
